### ISSUE TITLE
Hi, i found a bug

### ISSUE THREAD

**Issue by eduardoclaro99** [moto-msm8937/android_device_motorola_montana#1]
Hello
I test Lineage OS for montana
and I noticed a bug
when using the fingerprint as a navigation button the device heats up a lot, it gets slow and locks up forcing me to press the power until it turns off, other than that it's very stable, good job

**Comment by wiktorek140** [comment]
Missing logs. Missing build number. Missing kernel version. Probably will be closed beacuse its cannot be reproduced. I never spot error like this. Maybe your fingerprint is faulty thats why

**Comment by eduardoclaro99** [comment]
sorry, first time reporting a bug
Kernel: 3.18.140-perf-gbc58d07
build: 18.1-20210906-NIGTHLY-montana
model: XT1792
my fingerprint is ok, I have disabled the fingerprint navigation and I am using gestures, so far it hasn't warmed up or crashed the system

**Comment by JarlPenguin** [comment]
Can't reproduce. Without logs when the crash happens this will have to be closed.
